### ISSUE TITLE
Keeps components of the screens that have been popped out of the backstack in memory

### ISSUE THREAD

**Issue by arthurdanielyan** [arkivanov/Decompose#874]
Am I missing something or is this an issue?

<img width="1435" alt="Image" src="https://github.com/user-attachments/assets/0cf64bd7-9f8a-4bc5-85ff-97c737113fb6" />

When the screen using the component `SongsSetComponentImpl` gets popped out of the backstack `SongsSetComponentImpl` still remains in the memory according to Android Studio's profiler. This is the code where that component is used

```
@Composable
fun LocalScreen(
    component: LocalComponent,
) {
    Children(
        stack = component.childStack,
        animation = stackAnimation(slide()),
    ) {
        when (val childComponent = it.instance) {
            is LocalHomeComponent -> LocalHomeScreen(childComponent)
            is SongsSetComponent -> SongsSetScreen(childComponent)
        }
    }
}
```

`pushNew` and `pop` are called on the `StackNavigation`

**Comment by arkivanov** [comment]
Popped components should be released. How do you manage the stack?

**Comment by arthurdanielyan** [comment]
I created a minimal reproducable example, here's the [repo](https://github.com/arthurdanielyan/DecomposeMRE)
Also I'm attaching a [video](https://drive.google.com/file/d/1yn-WOfzsnGfjl7vJXZ_8PGoXBJrcA-Nl/view?usp=sharing) (couldn't upload on GitHub directly) on how I'm tracking the heap. Note that unused component only remains in heap when you use stackAnimation

**Comment by arkivanov** [comment]
Thanks for the reproducer! I've checked it and didn't notice anything unusual. Make sure you trigger GC a few times before launching the profiler, as unreferenced objects may be kept in memory for some time.

Also you mentioned the following:

> When the screen using the component SongsSetComponentImpl gets popped out of the backstack SongsSetComponentImpl still remains in the memory according to Android Studio's profiler.

However, I couldn't find the mentioned component in the screenshot you attached.

The easiest way to check for memory leaks is to allocate a large byte array in your component (like 50Mb array). Then when you pop the component, make sure you run GC a few times before capturing the heap dump. Then you shouldn't see any large objects. You can sort rows by Shallow Size for convenience.

```kotlin
class ScreenBComponent(
    componentContext: ComponentContext
) : ComponentContext by componentContext {
    val arr = ByteArray(100000000)
}
```

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/e087c889-7ece-4b00-9dd2-e4fd02ed5d3a" />

Let me know if there are still any issues!

**Comment by arthurdanielyan** [comment]
I added the 100MB array to the component as you suggested. After popping and forcing GC multiple times (as shown in the video), the component is still retained - screenshot attached.

<img width="1423" alt="Image" src="https://github.com/user-attachments/assets/beb80dca-0b3d-4647-9ba8-227b3991c362" />

<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/e1b6f978-7c73-4d8e-98b4-fe44a8d7b85e" />

You can see SongsSetComponentImpl at the top-left of the screenshot and its references on the right. The sample in the original screenshot isn't the reproducer repo, but it behaves identically - and the only change needed to avoid the leak is removing the stackAnimation. Everything disposes properly without it.

**Comment by arthurdanielyan** [comment]
Quick update - I realized I forgot to apply the stackAnimation line in the MRE repo. That’s probably why you didn’t see the leak there. I’ve updated the sample and re-tested it: the component is retained when stackAnimation is used and released properly when it's removed.

I've already pushed the updated MRE - the behavior is fully consistent with what I showed in the screenshots above.

**Comment by arkivanov** [comment]
> I realized I forgot to apply the stackAnimation line in the MRE repo

Indeed, this was the key point. Thanks for the info, I was able to reproduce.

Good news: the issue seems not reproducible with Decompose version 3.3.0 and the new [`ChildStack {}` Composable API](https://arkivanov.github.io/Decompose/extensions/compose/#the-new-experimental-animation-api). Please try using that instead.

Bad news: it's still reproducible with the old `Children {}` Composable API. This looks like a bug in Compose. I will check this issue deeper and provide more updates.

**Comment by arkivanov** [comment]
I have reported this as a bug here: https://issuetracker.google.com/issues/418214605. Will try to find a workaround.

**Comment by arkivanov** [comment]
Reported this as a bug: https://issuetracker.google.com/issues/418516940

**Comment by arkivanov** [comment]
Closing this for now as it looks like a bug in Compose and a workaround seems available. Feel free to reopen of there are any additional concerns.

**Comment by Ilya193** [comment]
The issue is reproduced with Decompose 3.3 and the new Child Stack. It is enough to add a click that will refer to the component

**Comment by arkivanov** [comment]
Thanks for the info. I've checked this case and it seems the same as already reported: https://issuetracker.google.com/issues/418516940

Confirmed as a bug in Compose.

**Comment by arkivanov** [comment]
The bug linked above has been marked as fixed!

**Comment by Ilya193** [comment]
composeBom = "2025.08.00"

implementation("com.arkivanov.decompose:extensions-compose-experimental:3.3.0")
implementation("com.arkivanov.decompose:extensions-compose-android:3.3.0")
implementation("com.arkivanov.decompose:decompose-android:3.3.0")
implementation("com.arkivanov.decompose:extensions-android:3.3.0")
https://issuetracker.google.com/issues/418516940

the problem with the code from issue is no longer reproducible, but is reproducible with decompose
could you check?

**Comment by arkivanov** [comment]
Thanks for the update! It seems there are more memory leaks in Compose. I will create a reproducer for them and file a new bug. Will update here.

**Comment by arkivanov** [comment]
Filed [b/438613819](https://issuetracker.google.com/issues/438613819).
